{{- $name := "php" -}}
{{- $data := dict "name" $name "Chart" .Chart "Release" .Release "Values" .Values -}}
apiVersion: v1
kind: Service
metadata:
  # /!\ To be reachable by NGINX, the service name MUST be hardcoded.
  # /!\ To deploy several instances in the same namespace you MUST rename the service here and in api/docker/nginx/conf.d/default.conf
  name: {{ $name }}
  labels:
    {{- include "api.labels" $data | nindent 4 }}
spec:
  type: {{ .Values.php.service.type }}
  ports:
    - port: {{ .Values.php.service.port }}
  selector:
    {{- include "api.selectorLabels" $data | nindent 4 }}
