sudo: required

services:
    - docker

script:
    - docker-compose build
    - docker-compose run --user=www-data --rm web composer install -o -n
    - docker-compose run --user=www-data --rm web bin/console security:check
