sudo: required

services:
    - docker

script:
    - docker-compose build
    - docker-compose run api composer install -o -n
    - docker-compose run api bin/console security:check
    - docker-compose run api bin/console doctrine:schema:create
    - docker-compose run api bin/console doctrine:mapping:info
    - docker-compose run api bin/console doctrine:schema:validate
    - docker-compose run api bin/console hautelook_alice:doctrine:fixtures:load -n
