sudo: required

services:
    - docker

script:
    - docker-compose build
    - docker-compose run --rm php chown -R $(id -u):$(id -g) .
    - touch src/foobar && rm src/foobar
    - docker-compose run --rm php composer install -o -n
    - docker-compose run --rm php bin/console cache:clear
    - docker-compose run --rm php bin/console security:check
