version: "3.8"

# Production environment override
services:
  php:
    build:
      context: ./api
      target: php_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET}

  pwa:
    build:
      context: ./pwa
      target: prod
    environment:
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}

  caddy:
    build:
      context: ./api/
      target: caddy_prod
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}

  database:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  keycloak-database:
    environment:
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}

  keycloak:
    environment:
      KEYCLOAK_PRODUCTION: "true"
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

