version: "2"

services:
  api:
      build: ./
      environment:
          SYMFONY_ENV: dev
      links:
          - db
      volumes:
          - ./:/app

  db:
      image: mysql
      environment:
          MYSQL_ROOT_PASSWORD: changeme
          MYSQL_DATABASE: api_platform
          MYSQL_USER: api_platform
          MYSQL_PASSWORD: api_platform
