version: '3'

services:
  db:
    image: mysql:8.0
    # Temporary fix, see https://github.com/docker-library/mysql/issues/284
    entrypoint: ['/entrypoint.sh', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
    environment:
      MYSQL_DATABASE: api_platform
      MYSQL_USER: api_platform
      MYSQL_PASSWORD: api_platform
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: mysql --user=api_platform --password=api_platform -e "SELECT 1" api_platform

  php:
    build: .
    depends_on:
      - db
    environment:
      SYMFONY_ENV: dev
    volumes:
      - ./:/srv/api-platform
      # For production only:
      #- ./var/cache:/srv/api-platform/var/cache
      #- ./var/logs:/srv/api-platform/var/logs
      #- ./var/sessions:/srv/api-platform/var/sessions
      #- ./var:/srv/api-platform/var
      #- ./vendor:/srv/api-platform/vendor
      #- ./web:/srv/api-platform/web

  nginx:
    image: nginx:1.11-alpine
    depends_on:
      - php
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./:/srv/api-platform

volumes:
  db-data:
