api_platform:
    title: Hello API Platform
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure: ~
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            max_age: 0
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true

when@prod:
    defaults:
        cache_headers:
            shared_max_age: 3600
    http_cache:
        public: true
        invalidation:
            enabled: true
            purger: 'api_platform.http_cache.purger.souin'
            urls: ['%env(SOUIN_API_URL)%']