name: CI

on: [push]

env:
  DOCKER_BUILDX_VERSION: '0.3.1'
  DOCKER_COMPOSE_VERSION: '1.25.2'
  DOCKER_REGISTRY: quay.io

jobs:
  docker-build-test-deploy:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate composer.json
        uses: docker-compose run --no-deps --rm -T php composer validate --no-check-publish
      - name: Start Api
        uses: docker-compose up -d api db
      
