name: Build environment
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: Validate composer.json
       run: docker-compose run --no-deps --rm -T php composer validate --no-check-publish
     - name: Start services
       run: docker-compose up -d
