name: Improve Code Style
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Improve Code Style
        uses: StephaneBour/actions-php-cs-fixer@1.0
        with:
          dir: api/src/
      - name: Tools
        uses: shivammathur/setup-php@v1
        with:
        php-version: '7.4'
        tools: php-cs-fixer, phpunit
