name: Code Style

on: [push]

jobs:
  check_code_quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Enviorement
        run : docker-compose up -d api 
      - name: PHP CS Fixer
        uses: ./.github/actions/phpcsfixer
      - name: PHP Insights
        run: docker-compose exec -T php ./vendor/bin/phpinsights --no-interaction --min-quality=80 --min-complexity=80 --min-architecture=80 --min-style=80
      - uses: stefanzweifel/git-auto-commit-action@v2.1.0
        with:
          commit_message: Apply php-cs-fixer changes
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
