name: Improve Code Style
on: [push]

jobs:
  steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Improve Code Style
      uses: StephaneBour/actions-php-cs-fixer@1.0
      with:
        dir: api/src/
