name: Testing CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Validate composer.json'
        run: composer validate
      - name: 'Install deps'
        run: composer install
