name: Testing CI

on:
  push:
    branches:
      - master   

jobs:
  build:
     runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v1

  - name: Validate composer.json
    run: composer validate
  - name: Install dependencies
    run: composer install  
