name: Testing CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: 'Validate composer.json'
        working-directory: 'api/'
        run: composer validate
      - name: 'Install deps'
        working-directory: 'api/'
        run: composer install
        
